name: Deploy SlackBot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ec2-user@ec2-3-135-199-118.us-east-2.compute.amazonaws.com:~/slackbot/

    - name: Set OpenAI API Key
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ~/slackbot/.env

    - name: Install Dependencies on EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ec2-user@ec2-3-135-199-118.us-east-2.compute.amazonaws.com:~/slackbot/
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-135-199-118.us-east-2.compute.amazonaws.com "cd ~/slackbot && pip3 install -r requirements.txt"
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-135-199-118.us-east-2.compute.amazonaws.com "pkill -f slackBot.py || true && nohup python3 slackBot.py &"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
