name: Deploy SlackBot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy Files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./ ec2-user@<EC2-PUBLIC-IP>:~/slackbot/

    - name: Install Dependencies on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<EC2-PUBLIC-IP> <<EOF
        cd ~/slackbot
        pip3 install -r requirements.txt
        pkill -f slackBot.py || true
        nohup python3 slackBot.py &
        EOF
